fix error in some previous versions of Chrome
mdittmer/object-graph-js pull request #3
Opened 2017-01-19 19:44 UTC by jingt06

- add blacklistedTypes
- property is blacklisted if type is MimeType

2017-01-20 15:06 UTC, mdittmer requested changes
This is almost ready. Just one nit.

Before mergine, please:

(1) Create an issue detailing the problem you're seeing in old version of Chrome.
(2) Mention the issue # in a comment on this PR.

Don't mark the issue as fixed yet. We should investigate *exactly* what's going on with Mime types and try to capture that data exactly once, rather than excluding it.

2017-01-20 15:06 UTC, mdittmer commented on src/ObjectGraph.es6.js
> +  'MimeType'   // causing error in some previous versions of Chrome
nit: whenever possible, phrase comment as a sentence (start with capital letter, end with period). Also, please be more specific; e.g.,

"This type initiates a process of continually extending the object graphs in Chrome <= [[largest version number with issue]]."

2017-01-20 15:16 UTC, jingt06 commented
Issue #4

2017-01-20 16:16 UTC, mdittmer requested changes
Just some more comment clarification stuff.

2017-01-20 16:16 UTC, mdittmer commented on src/ObjectGraph.es6.js
> +               // extending the object graphs in Chrome
What's the largest version number where this issue occurs? I think we should include it in the comment.

nit: Still missing period at end of comment.

2017-01-23 17:10 UTC, mdittmer approved these changes
LGTM!

2017-01-23 17:11 UTC, merged