Object graph include function names
mdittmer/object-graph-js pull request #6
Opened 2017-01-27 20:26 UTC by jingt06

- Change Object Graph structure: 
    - functions is a map of form {id: functionName}.
- some useful methods:
    - getFunctionName: Get name of a given function id.
   -  getRoot: Get the root id.
   -  getPropertiesIds: Get the properties and id belong to the given id.

2017-01-29 16:22 UTC, mdittmer commented on src/ObjectGraph.es6.js
> +          function(a){return a!==''}
nit: spacing `function() { a !== ''; }`.

2017-01-29 16:22 UTC, mdittmer commented on src/ObjectGraph.es6.js
> +  clone.functions = _.cloneDeep(this.functions);
Let's put function metadata in `metadata`.

2017-01-29 16:22 UTC, mdittmer commented on src/ObjectGraph.es6.js
> +  return this.data[id]
I'm a little anxious about exposing the raw data object for clients to muck with. Perhaps `Object.assign({}, this.data[id])`?

2017-01-29 16:22 UTC, mdittmer commented on src/ObjectGraph.es6.js
> +});
Please configure your editor to include a newline at the end of every file.

2017-01-29 16:23 UTC, mdittmer requested changes
Requested a few minor changes to consolidate metadata and avoid providing write access to raw data.

2017-01-30 15:33 UTC, jingt06 commented
fixed @mdittmer

2017-02-01 21:00 UTC, mdittmer requested changes
Preamble: My apologies for asking you to change-then-change-back on one point here.

I forgot that `metadata` is property-level, not object-level (i.e., `metadata[id][property-name] = property-metadata`). In light of this, we should probably store `functions` separately as you had before. Please keep the change with `Object.assign(...)` though.

2017-02-02 15:41 UTC, jingt06 commented
Moved functions out of metadata. @mdittmer

2017-02-02 17:40 UTC, mdittmer approved these changes
LGTM

2017-02-02 17:41 UTC, merged