blacklist object and $UID exposed from Foam
mdittmer/object-graph-js pull request #8
Opened 2017-02-06 15:58 UTC by jingt06

2017-02-06 22:04 UTC, mdittmer requested changes

2017-02-06 22:04 UTC, mdittmer commented on src/ObjectGraph.es6.js
> +  '$UID', '$UID__']; // Foam assigns unique Ids to objects.
Please clarify that this refers to the last two keys in the list. Also, please add a TODO to upstream id-js to FOAM so we don't have two unique identifiers floating around.

2017-02-06 22:04 UTC, mdittmer commented on src/ObjectGraph.es6.js
> +  '$UID', '$UID__']; // Foam assigns unique Ids to objects.
Nit: here and below, capitalization is "FOAM Framework"

2017-02-07 18:01 UTC, jingt06 commented on src/ObjectGraph.es6.js
> +  '$UID', '$UID__']; // Foam assigns unique Ids to objects.
Fixed

2017-02-08 20:47 UTC, mdittmer approved these changes
Please fix nit, then LGTM!

2017-02-08 20:47 UTC, mdittmer commented on src/ObjectGraph.es6.js
> +  '$UID__']; // TODO: Upstream id-js to FOAM so we don't have two unique ids.
nit: Please add trailing comma and close array literal on its own line.

2017-02-08 20:53 UTC, merged